<?xml version="1.0"?>
<GrockartLog>
  <log>
    <level>WARN</level>
    <date>03-07-2018 19:54:30</date>
    <exceptionType>LoginException</exceptionType>
    <functionName>LoginUser</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs</fileLocation>
    <lineNumber>215</lineNumber>
    <message>Unable to login to the system, please try again later. This event has been logged</message>
    <stackTrace>Grockart.CUSTOM_EXCEPTIONS.LoginException: Unable to login to the system, please try again later. This event has been logged
   at Grockart.BUSINESSLAYER.UserFactory.LoginUser(String email, String password) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs:line 215</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 19:54:30</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 64</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 19:54:21</date>
    <exceptionType>NullReferenceException</exceptionType>
    <functionName>get_GetDBVersion</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs</fileLocation>
    <lineNumber>34</lineNumber>
    <message>object reference not set to an instance of an object.</message>
    <stackTrace>System.NullReferenceException: object reference not set to an instance of an object.
   at Grockart.BUSINESSLAYER.DBVersion.get_GetDBVersion() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs:line 34</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 19:54:21</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 64</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 19:54:17</date>
    <exceptionType>NullReferenceException</exceptionType>
    <functionName>get_GetDBVersion</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs</fileLocation>
    <lineNumber>34</lineNumber>
    <message>object reference not set to an instance of an object.</message>
    <stackTrace>System.NullReferenceException: object reference not set to an instance of an object.
   at Grockart.BUSINESSLAYER.DBVersion.get_GetDBVersion() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs:line 34</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 19:54:17</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 64</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 18:22:19</date>
    <exceptionType>LoginException</exceptionType>
    <functionName>LoginUser</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs</fileLocation>
    <lineNumber>219</lineNumber>
    <message>Unable to login to the system, please try again later. This event has been logged</message>
    <stackTrace>Grockart.CUSTOM_EXCEPTIONS.LoginException: Unable to login to the system, please try again later. This event has been logged
   at Grockart.BUSINESSLAYER.UserFactory.LoginUser(String email, String password) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs:line 219</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:22:19</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 18:22:10</date>
    <exceptionType>LoginException</exceptionType>
    <functionName>LoginUser</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs</fileLocation>
    <lineNumber>219</lineNumber>
    <message>Unable to login to the system, please try again later. This event has been logged</message>
    <stackTrace>Grockart.CUSTOM_EXCEPTIONS.LoginException: Unable to login to the system, please try again later. This event has been logged
   at Grockart.BUSINESSLAYER.UserFactory.LoginUser(String email, String password) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs:line 219</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:22:10</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:20:00</date>
    <exceptionType>LoginException</exceptionType>
    <functionName>LoginUser</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs</fileLocation>
    <lineNumber>219</lineNumber>
    <message>Unable to login to the system, please try again later. This event has been logged</message>
    <stackTrace>Grockart.CUSTOM_EXCEPTIONS.LoginException: Unable to login to the system, please try again later. This event has been logged
   at Grockart.BUSINESSLAYER.UserFactory.LoginUser(String email, String password) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\UserFactory.cs:line 219</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:20:00</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:19:54</date>
    <exceptionType>NullReferenceException</exceptionType>
    <functionName>get_GetDBVersion</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs</fileLocation>
    <lineNumber>34</lineNumber>
    <message>object reference not set to an instance of an object.</message>
    <stackTrace>System.NullReferenceException: object reference not set to an instance of an object.
   at Grockart.BUSINESSLAYER.DBVersion.get_GetDBVersion() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs:line 34</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:19:54</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:19:29</date>
    <exceptionType>NullReferenceException</exceptionType>
    <functionName>get_GetDBVersion</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs</fileLocation>
    <lineNumber>34</lineNumber>
    <message>object reference not set to an instance of an object.</message>
    <stackTrace>System.NullReferenceException: object reference not set to an instance of an object.
   at Grockart.BUSINESSLAYER.DBVersion.get_GetDBVersion() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\DBVersion.cs:line 34</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 18:19:29</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>AuthenticationFailed</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'db-5308.cs.dal.ca' for user 'CSCI53208_10_TEST_USER' using method 'mysql_native_password' failed with message: Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES) ---&gt; MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'CSCI53208_10_TEST_USER'@'24-224-253-87.eastlink.ca' (using password: YES)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 17:19:20</date>
    <exceptionType>Exception</exceptionType>
    <functionName>GetMenu</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\GrokartMenu.cs</fileLocation>
    <lineNumber>22</lineNumber>
    <message>GetMenu() function in MySQLUserDataLayer returned null, please check the stored procedure and function</message>
    <stackTrace>System.Exception: GetMenu() function in MySQLUserDataLayer returned null, please check the stored procedure and function
   at Grockart.BUSINESSLAYER.GrokartMenu.GetMenu() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\GrokartMenu.cs:line 22</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 17:19:20</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>GetProcData</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.
   at MySql.Data.MySqlClient.ProcedureCache.GetProcData(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.AddNew(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.GetProcedure(MySqlConnection conn, String spName, String cacheKey)
   at MySql.Data.MySqlClient.StoredProcedure.GetParameters(String procName)
   at MySql.Data.MySqlClient.StoredProcedure.CheckParameters(String spName)
   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 17:07:57</date>
    <exceptionType>Exception</exceptionType>
    <functionName>GetMenu</functionName>
    <fileLocation>C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\GrokartMenu.cs</fileLocation>
    <lineNumber>22</lineNumber>
    <message>GetMenu() function in MySQLUserDataLayer returned null, please check the stored procedure and function</message>
    <stackTrace>System.Exception: GetMenu() function in MySQLUserDataLayer returned null, please check the stored procedure and function
   at Grockart.BUSINESSLAYER.GrokartMenu.GetMenu() in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.BUSINESSLAYER\GrokartMenu.cs:line 22</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 17:07:57</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>GetProcData</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.
   at MySql.Data.MySqlClient.ProcedureCache.GetProcData(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.AddNew(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.GetProcedure(MySqlConnection conn, String spName, String cacheKey)
   at MySql.Data.MySqlClient.StoredProcedure.GetParameters(String procName)
   at MySql.Data.MySqlClient.StoredProcedure.CheckParameters(String spName)
   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>FATAL</level>
    <date>03-07-2018 17:05:25</date>
    <exceptionType>MySqlException</exceptionType>
    <functionName>GetProcData</functionName>
    <fileLocation>
    </fileLocation>
    <lineNumber>0</lineNumber>
    <message>Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.</message>
    <stackTrace>MySql.Data.MySqlClient.MySqlException (0x80004005): Procedure or function '`sp_getMenu1`' cannot be found in database '`CSCI5308_10_TEST`'.
   at MySql.Data.MySqlClient.ProcedureCache.GetProcData(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.AddNew(MySqlConnection connection, String spName)
   at MySql.Data.MySqlClient.ProcedureCache.GetProcedure(MySqlConnection conn, String spName, String cacheKey)
   at MySql.Data.MySqlClient.StoredProcedure.GetParameters(String procName)
   at MySql.Data.MySqlClient.StoredProcedure.CheckParameters(String spName)
   at MySql.Data.MySqlClient.StoredProcedure.Resolve(Boolean preparing)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Grockart.DATALAYER.MySQLCommands.ExecuteQuery(IConnection SQLConnection, String commandText, object commandType, object[] commandParameters) in C:\Users\deep_\Source\Repos\Group10\grockart\Grockart.DATALAYER\MySQLCommands.cs:line 68</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 16:50:36</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 16:48:46</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 16:44:41</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 16:34:33</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 16:33:51</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 15:59:56</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
  <log>
    <level>WARN</level>
    <date>03-07-2018 15:57:27</date>
    <exceptionType>Exception</exceptionType>
    <functionName>Page_Load</functionName>
    <fileLocation>c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs</fileLocation>
    <lineNumber>48</lineNumber>
    <message>Exception of type 'System.Exception' was thrown.</message>
    <stackTrace>System.Exception: Exception of type 'System.Exception' was thrown.
   at main.Page_Load(object sender, EventArgs e) in c:\Users\deep_\source\repos\Group10\grockart\grockart\main.master.cs:line 48</stackTrace>
  </log>
</GrockartLog>